image: python:3.11-slim

stages:
  - test
  - docker-build

.before_script_template: &setup
  before_script:
    - apt update
    - apt install gcc

.before_script_template: &configure_poetry
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry config virtualenvs.in-project true
    - poetry install

cache:
  paths:
    - .venv

test:
  stage: test
  <<: *setup
  <<: *configure_poetry
  script:
    - poetry run pytest -v

docker build:
  stage: docker-build
  image: docker:20.10-dind
  services:
    - docker:dind
  script:
    - docker compose build
  only:
    - tags
