image: python:3.11-slim

stages:
  - test
  - docker-build

.before_script_template: &setup
  - apt update
  - apt install -y gcc git
  - git --version # debug

.before_script_template: &configure_poetry
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry config virtualenvs.in-project true
  - poetry install

cache:
  paths:
    - .venv

test:
  stage: test
  before_script:
    - *setup
    - *configure_poetry
  script:
    - poetry run pytest -v

docker build:
  stage: docker-build
  image: docker:20.10-dind
  services:
    - docker:dind
  script:
    - docker compose build
  only:
    - tags
