build and test:
  image: docker:20.10-dind
  services:
    - docker:dind
  before_script:
    - cp .env.example .env
  script:
    - docker compose build
    - docker compose up -d
    - docker exec yonei-dev pytest /project
