version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
    container_name: "yonei-dev"
    environment:
        DEBUG: ${DEBUG}
    ports:
      - "8080:8000"
    volumes:
      - ./app:/project/app
      - ./posts:/project/posts
