version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - ENVIROMENT=${ENVIROMENT}
    container_name: "yonei-dev"
    environment:
        ENVIROMENT: ${ENVIROMENT}
        DEBUG: ${DEBUG}
    ports:
      - "8080:8000"
    volumes:
      - ./app:/project/app
      - ./posts:/project/posts:ro
    restart: unless-stopped
