version: "3.8"

services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    container_name: "yonei-dev"
    ports:
      - "8080:8000"
    volumes:
      - .env:/project/.env:ro
      - ./app:/project/app
      - ./posts:/project/posts:ro
    restart: unless-stopped
